tests:
[
  {
    robotstxt: "USER-AGENT: FooBot\nALLOW: /x/\nDISALLOW: /\n"
    test_expectations:
    [
      {
        testurl: "http://foo.bar/x/y"
        useragent: "FooBot"
        expected_outcome: ALLOWED
        additional_explanation: "REP lines are case insensitive. See REP I-D section \"Protocol Definition\"."
      },
      {
        testurl: "http://foo.bar/a/b"
        useragent: "FooBot"
        expected_outcome: DISALLOWED
        additional_explanation: "REP lines are case insensitive. See REP I-D section \"Protocol Definition\"."
      }
    ]
  },
  {
    robotstxt: "user-agent: FooBot\nallow: /x/\ndisallow: /\n"
    test_expectations:
    [
      {
        testurl: "http://foo.bar/x/y"
        useragent: "FooBot"
        expected_outcome: ALLOWED
        additional_explanation: "REP lines are case insensitive. See REP I-D section \"Protocol Definition\"."
      },
      {
        testurl: "http://foo.bar/a/b"
        useragent: "FooBot"
        expected_outcome: DISALLOWED
        additional_explanation: "REP lines are case insensitive. See REP I-D section \"Protocol Definition\"."
      }
    ]
  },
  {
    robotstxt: "uSeR-aGeNt: FooBot\nAlLoW: /x/\ndIsAlLoW: /\n"
    test_expectations:
    [
      {
        testurl: "http://foo.bar/x/y"
        useragent: "FooBot"
        expected_outcome: ALLOWED
        additional_explanation: "REP lines are case insensitive. See REP I-D section \"Protocol Definition\"."
      },
      {
        testurl: "http://foo.bar/a/b"
        useragent: "FooBot"
        expected_outcome: DISALLOWED
        additional_explanation: "REP lines are case insensitive. See REP I-D section \"Protocol Definition\"."
      }
    ]
  }
]
