tests:
[
  {
    robotstxt: ""
    test_expectations:
    [
      {
        testurl: ""
        useragent: "FooBot"
        expected_outcome: ALLOWED
        additional_explanation: "Empty robots.txt: everything allowed."
      },
      {
        testurl: ""
        useragent: ""
        expected_outcome: ALLOWED
        additional_explanation: "All params empty: same as robots.txt empty, everything allowed."
      }
    ]
  },
  {
    robotstxt: "user-agent: FooBot\ndisallow: /\n"
    test_expectations:
    [
      {
        testurl: ""
        useragent: ""
        expected_outcome: ALLOWED
        additional_explanation: "Empty user-agent to be matched: everything allowed."
      },
      {
        testurl: ""
        useragent: "FooBot"
        expected_outcome: DISALLOWED
        additional_explanation: "Empty url: implicitly disallowed"
      }
    ]
  }
]
