tests:
[
  {
    robotstxt: "User-Agent: *\nDisallow: /\nUser-Agent: Foo Bar\nAllow: /x/\nDisallow: /\n"
    test_expectations:
    [
      {
        testurl: "http://foo.bar/x/y"
        useragent: "Foo"
        expected_outcome: ALLOWED
        additional_explanation: "Google specific: accept user-agent value up to the first space."
      },
      {
        testurl: "http://foo.bar/x/y"
        useragent: "Foo Bar"
        expected_outcome: DISALLOWED
        additional_explanation: "Google specific: accept user-agent value up to the first space."
      }
    ]
  },
  {
    robotstxt: "user-agent: FOO BAR\nallow: /x/\ndisallow: /\n"
    test_expectations:
    [
      {
        testurl: "http://foo.bar/x/y"
        useragent: "Foo"
        expected_outcome: ALLOWED
        additional_explanation: "User-agent line values are case insensitive.\nGoogle specific: accept user-agent value up to the first space."
      },
      {
        testurl: "http://foo.bar/x/y"
        useragent: "foo"
        expected_outcome: ALLOWED
        additional_explanation: "User-agent line values are case insensitive.\nGoogle specific: accept user-agent value up to the first space."
      },
      {
        testurl: "http://foo.bar/a/b"
        useragent: "Foo"
        expected_outcome: DISALLOWED
        additional_explanation: "User-agent line values are case insensitive.\nGoogle specific: accept user-agent value up to the first space."
      },
      {
        testurl: "http://foo.bar/a/b"
        useragent: "foo"
        expected_outcome: DISALLOWED
        additional_explanation: "User-agent line values are case insensitive.\nGoogle specific: accept user-agent value up to the first space."
      }
    ]
  },
  {
    robotstxt: "user-agent: foo bar\nallow: /x/\ndisallow: /\n"
    test_expectations:
    [
      {
        testurl: "http://foo.bar/x/y"
        useragent: "Foo"
        expected_outcome: ALLOWED
        additional_explanation: "User-agent line values are case insensitive.\nGoogle specific: accept user-agent value up to the first space."
      },
      {
        testurl: "http://foo.bar/x/y"
        useragent: "foo"
        expected_outcome: ALLOWED
        additional_explanation: "User-agent line values are case insensitive.\nGoogle specific: accept user-agent value up to the first space."
      },
      {
        testurl: "http://foo.bar/a/b"
        useragent: "Foo"
        expected_outcome: DISALLOWED
        additional_explanation: "User-agent line values are case insensitive.\nGoogle specific: accept user-agent value up to the first space."
      },
      {
        testurl: "http://foo.bar/a/b"
        useragent: "foo"
        expected_outcome: DISALLOWED
        additional_explanation: "User-agent line values are case insensitive.\nGoogle specific: accept user-agent value up to the first space."
      }
    ]
  },
  {
    robotstxt: "user-agent: FoO bAr\nallow: /x/\ndisallow: /\n"
    test_expectations:
    [
      {
        testurl: "http://foo.bar/x/y"
        useragent: "Foo"
        expected_outcome: ALLOWED
        additional_explanation: "User-agent line values are case insensitive.\nGoogle specific: accept user-agent value up to the first space."
      },
      {
        testurl: "http://foo.bar/x/y"
        useragent: "foo"
        expected_outcome: ALLOWED
        additional_explanation: "User-agent line values are case insensitive.\nGoogle specific: accept user-agent value up to the first space."
      },
      {
        testurl: "http://foo.bar/a/b"
        useragent: "Foo"
        expected_outcome: DISALLOWED
        additional_explanation: "User-agent line values are case insensitive.\nGoogle specific: accept user-agent value up to the first space."
      },
      {
        testurl: "http://foo.bar/a/b"
        useragent: "foo"
        expected_outcome: DISALLOWED
        additional_explanation: "User-agent line values are case insensitive.\nGoogle specific: accept user-agent value up to the first space."
      }
    ]
  }
]
