# proto-file: src/main/proto/specification/specification.proto
# proto-message: specification.RobotsTxtSpecification
tests:
[
  {
    robotstxt: "User-Agent: *\n"
        "Disallow: /\n"
        "User-Agent: Foo Bar\n"
        "Allow: /x/\n"
        "Disallow: /\n"
    test_expectations:
    [
      {
        testurl: "http://foo.bar/x/y"
        useragent: "Foo"
        expected_outcome: ALLOWED
        additional_explanation: "Google specific: accept user-agent value up to the first space."
            "\nhttps://github.com/google/robotstxt/blob/master/robots.cc#L552"
        test_type: GOOGLE_SPECIFIC
      },
      {
        testurl: "http://foo.bar/x/y"
        useragent: "Foo Bar"
        expected_outcome: DISALLOWED
        additional_explanation: "Google specific: accept user-agent value up to the first space."
            "\nhttps://github.com/google/robotstxt/blob/master/robots.cc#L552"
        test_type: GOOGLE_SPECIFIC
      }
    ]
  },
  {
    robotstxt: "user-agent: FOO BAR\n"
        "allow: /x/\n"
        "disallow: /\n"
    test_expectations:
    [
      {
        testurl: "http://foo.bar/x/y"
        useragent: "Foo"
        expected_outcome: ALLOWED
        additional_explanation: "User-agent line values are case insensitive. "
            "See REP I-D section \"The user-agent line\":\n"
            "https://tools.ietf.org/html/draft-koster-rep#section-2.2.1\n"
            "Google specific: accept user-agent value up to the first space."
            "\nhttps://github.com/google/robotstxt/blob/master/robots.cc#L552"
        test_type: GOOGLE_SPECIFIC
      },
      {
        testurl: "http://foo.bar/x/y"
        useragent: "foo"
        expected_outcome: ALLOWED
        additional_explanation: "User-agent line values are case insensitive. "
            "See REP I-D section \"The user-agent line\":\n"
            "https://tools.ietf.org/html/draft-koster-rep#section-2.2.1\n"
            "Google specific: accept user-agent value up to the first space."
            "\nhttps://github.com/google/robotstxt/blob/master/robots.cc#L552"
        test_type: GOOGLE_SPECIFIC
      },
      {
        testurl: "http://foo.bar/a/b"
        useragent: "Foo"
        expected_outcome: DISALLOWED
        additional_explanation: "User-agent line values are case insensitive. "
            "See REP I-D section \"The user-agent line\":\n"
            "https://tools.ietf.org/html/draft-koster-rep#section-2.2.1\n"
            "Google specific: accept user-agent value up to the first space."
            "\nhttps://github.com/google/robotstxt/blob/master/robots.cc#L552"
        test_type: GOOGLE_SPECIFIC
      },
      {
        testurl: "http://foo.bar/a/b"
        useragent: "foo"
        expected_outcome: DISALLOWED
        additional_explanation: "User-agent line values are case insensitive. "
            "See REP I-D section \"The user-agent line\":\n"
            "https://tools.ietf.org/html/draft-koster-rep#section-2.2.1\n"
            "Google specific: accept user-agent value up to the first space."
            "\nhttps://github.com/google/robotstxt/blob/master/robots.cc#L552"
        test_type: GOOGLE_SPECIFIC
      }
    ]
  },
  {
    robotstxt: "user-agent: foo bar\n"
        "allow: /x/\n"
        "disallow: /\n"
    test_expectations:
    [
      {
        testurl: "http://foo.bar/x/y"
        useragent: "Foo"
        expected_outcome: ALLOWED
        additional_explanation: "User-agent line values are case insensitive. "
            "See REP I-D section \"The user-agent line\":\n"
            "https://tools.ietf.org/html/draft-koster-rep#section-2.2.1\n"
            "Google specific: accept user-agent value up to the first space."
            "\nhttps://github.com/google/robotstxt/blob/master/robots.cc#L552"
        test_type: GOOGLE_SPECIFIC
      },
      {
        testurl: "http://foo.bar/x/y"
        useragent: "foo"
        expected_outcome: ALLOWED
        additional_explanation: "User-agent line values are case insensitive. "
            "See REP I-D section \"The user-agent line\":\n"
            "https://tools.ietf.org/html/draft-koster-rep#section-2.2.1\n"
            "Google specific: accept user-agent value up to the first space."
            "\nhttps://github.com/google/robotstxt/blob/master/robots.cc#L552"
        test_type: GOOGLE_SPECIFIC
      },
      {
        testurl: "http://foo.bar/a/b"
        useragent: "Foo"
        expected_outcome: DISALLOWED
        additional_explanation: "User-agent line values are case insensitive. "
            "See REP I-D section \"The user-agent line\":\n"
            "https://tools.ietf.org/html/draft-koster-rep#section-2.2.1\n"
            "Google specific: accept user-agent value up to the first space."
            "\nhttps://github.com/google/robotstxt/blob/master/robots.cc#L552"
        test_type: GOOGLE_SPECIFIC
      },
      {
        testurl: "http://foo.bar/a/b"
        useragent: "foo"
        expected_outcome: DISALLOWED
        additional_explanation: "User-agent line values are case insensitive. "
            "See REP I-D section \"The user-agent line\":\n"
            "https://tools.ietf.org/html/draft-koster-rep#section-2.2.1\n"
            "Google specific: accept user-agent value up to the first space."
            "\nhttps://github.com/google/robotstxt/blob/master/robots.cc#L552"
        test_type: GOOGLE_SPECIFIC
      }
    ]
  },
  {
    robotstxt: "user-agent: FoO bAr\n"
        "allow: /x/\n"
        "disallow: /\n"
    test_expectations:
    [
      {
        testurl: "http://foo.bar/x/y"
        useragent: "Foo"
        expected_outcome: ALLOWED
        additional_explanation: "User-agent line values are case insensitive. "
            "See REP I-D section \"The user-agent line\":\n"
            "https://tools.ietf.org/html/draft-koster-rep#section-2.2.1\n"
            "Google specific: accept user-agent value up to the first space."
            "\nhttps://github.com/google/robotstxt/blob/master/robots.cc#L552"
        test_type: GOOGLE_SPECIFIC
      },
      {
        testurl: "http://foo.bar/x/y"
        useragent: "foo"
        expected_outcome: ALLOWED
        additional_explanation: "User-agent line values are case insensitive. "
            "See REP I-D section \"The user-agent line\":\n"
            "https://tools.ietf.org/html/draft-koster-rep#section-2.2.1\n"
            "Google specific: accept user-agent value up to the first space."
            "\nhttps://github.com/google/robotstxt/blob/master/robots.cc#L552"
        test_type: GOOGLE_SPECIFIC
      },
      {
        testurl: "http://foo.bar/a/b"
        useragent: "Foo"
        expected_outcome: DISALLOWED
        additional_explanation: "User-agent line values are case insensitive. "
            "See REP I-D section \"The user-agent line\":\n"
            "https://tools.ietf.org/html/draft-koster-rep#section-2.2.1\n"
            "Google specific: accept user-agent value up to the first space."
            "\nhttps://github.com/google/robotstxt/blob/master/robots.cc#L552"
        test_type: GOOGLE_SPECIFIC
      } ,
      {
        testurl: "http://foo.bar/a/b"
        useragent: "foo"
        expected_outcome: DISALLOWED
        additional_explanation: "User-agent line values are case insensitive. "
            "See REP I-D section \"The user-agent line\":\n"
            "https://tools.ietf.org/html/draft-koster-rep#section-2.2.1\n"
            "Google specific: accept user-agent value up to the first space."
            "\nhttps://github.com/google/robotstxt/blob/master/robots.cc#L552"
        test_type: GOOGLE_SPECIFIC
      }
    ]
  }
]
